/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fraud.detection;

import java.io.IOException;
import java.text.ParseException;

public class App {
    public static void main(String[] args) throws IOException, ParseException {

        var transactions = CsvFileReader.toTransactions(CsvFileReader.read("data/cumulativeTransactions.csv"));

        var result = FraudDetection.identify(transactions, Long.valueOf(86400), 10.0);

        System.out.println(result);
    }
}
